News/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from accounts.views import test_page
from .views import (
    PostList,
    PostDetail,
    NewsCreate,
    NewsUpdate,
    NewsDelete,
    CategoryListView,
    subscriptions,
    subscribe,
)


urlpatterns = [
    path("", cache_page(60)(PostList.as_view()), name="posts_list"),
    path("<int:pk>", cache_page(300)(PostDetail.as_view()), name="one_news"),
    path("search/", PostList.as_view()),
    path("create/", NewsCreate.as_view(), name="news_create"),
    path("<int:pk>/edit/", NewsUpdate.as_view(), name="news_update"),
    path("<int:pk>/delete/", NewsDelete.as_view(), name="news_delete"),
    path("test/", test_page, name="test_page"),
    path("subscriptions/", subscriptions, name="subscriptions"),
    # path('categories/', CategoryListView.as_view(), name='category_list'),
    path("categories/<int:pk>", CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/subscribe", subscribe, name="subscribe"),
]

NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from News import views
from News.views import ArticleCreate, ArticleUpdate, ArticleDelete

router = routers.DefaultRouter()
router.register(r"delete_news", views.NewsDeleteViewSet)
router.register(r"create_news", views.NewsCreateViewSet)
router.register(r"update_news", views.NewsUpdateViewSet)
router.register(r"create_article", views.ArticleCreateViewSet)
router.register(r"update_article", views.ArticleUpdateViewSet)
router.register(r"delete_article", views.ArticleDeleteViewSet)
router.register(r"subscription", views.SubscriptionViewViewSet)
router.register(r"category", views.CategoryListViewViewSet)
router.register(r"news", views.PostListViewSet)
router.register(r"authors", views.AuthorViewSet)
router.register(r"post", views.PostDetailViewSet)


urlpatterns = [
    path("", include("News.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("news/", include("News.urls")),
    path("accounts/", include("allauth.urls")),
    path("articles/create/", ArticleCreate.as_view(), name="article_create"),
    path("articles/<int:pk>/edit/", ArticleUpdate.as_view(), name="article_edit"),
    path("articles/<int:pk>/delete/", ArticleDelete.as_view(), name="article_delete"),
    path("api/", include(router.urls)),
]

News/models.py
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse
from django.utils.translation import gettext as _

from NewsPortal.settings import logger


# from .models import Category, MyModel


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    # rating__sum
    def update_rating(self):
        """
        Обновляет рейтинг текущего автора.

        Эта функция вычисляет рейтинг для автора текущего экземпляра,
        суммируя рейтинги постов, комментариев и комментариев к постам автора.
        Рейтинг вычисляется по следующей формуле:

        ratingAuthor = (authorPostRating * 3) + authorCommentRating + authorPostCommentRating

        Параметры:
            self (Author): Текущий экземпляр автора.

        Возвращает:
            None

        Выбрасывает:
            None
        """
        authorPostRating = Post.objects.filter(author_id=self.pk).aggregate(
            count=Coalesce(Sum("rating"), 0)
        )["count"]
        authorCommentRating = Comment.objects.filter(
            commentUser_id=self.authorUser
        ).aggregate(count=Coalesce(Sum("rating"), 0))["count"]
        authorPostCommentRating = Comment.objects.filter(
            commentPost__author__authorUser=self.authorUser
        ).aggregate(count=Coalesce(Sum("rating"), 0))["count"]

        self.ratingAuthor = (
            authorPostRating * 3 + authorCommentRating + authorPostCommentRating
        )
        self.save()

    def __str__(self):
        """
        Возвращает имя пользователя автора в виде строки.

        return: Строка, представляющая имя пользователя автора.
        """
        return self.authorUser.username

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True, help_text=_("category name"))
    subscribers = models.ManyToManyField(User, related_name="categories")

    def __str__(self):
        """
        Возвращает строковое представление объекта.
        return: Строка, представляющая имя объекта.
        """
        logger.info(f"Category: {self.name}")
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Post(models.Model):
    NEWS = "NW"
    ARTICLE = "AR"
    CATEGORY_CHOICES = (
        (NEWS, "Новость"),
        (ARTICLE, "Статья"),
    )
    dateCreation = models.DateTimeField(auto_now_add=True)
    categoryType = models.CharField(
        max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE
    )
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="posts")
    postCategory = models.ManyToManyField(Category, through="PostCategory")
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        """
        Возвращает строковое представление объекта.

        Этот метод переопределяет встроенный метод `__str__` для предоставления
        пользовательского строкового представления объекта. Он объединяет имя
        пользователя автора, заголовок поста и первые 123 символа текста поста,
        за которым следует многоточие.

        Возвращает:
            str: Строковое представление объекта.
        """
        logger.info(f"Post: {self.title}")
        return (
            f"{self.author.authorUser.username} : {self.title} : {self.text[0:123]}..."
        )

    def save(self, *args, **kwargs):
        """
        Сохраняет экземпляр в базе данных и удаляет кэш
        для соответствующего объекта новости.

        Параметры:
            *args: Переменное число позиционных аргументов.
            **kwargs: Произвольное число именованных аргументов.

        Возвращает:
            None
        """
        super().save(*args, **kwargs)
        cache.delete(f"news-{self.pk}")

    def get_absolute_url(self):
        """
        Генерирует абсолютный URL для текущего объекта.
        Эта функция использует функцию reverse() для генерации URL-шаблона для
        представления 'one_news', передавая ID текущего объекта в качестве аргумента.

        Параметры:
            self (object): Текущий объект.

        Возвращает:
            str: Абсолютный URL для текущего объекта.
        """
        logger.info(f"URL: {self.get_absolute_url()}")
        return reverse("one_news", args=[str(self.id)])

    def like(self):
        """
        Увеличивает значение поля `rating` текущего объекта на 1 и сохраняет изменения.

        Параметры:
            Нет

        Возвращает:
            Ничего
        """
        self.rating = models.F("rating") + 1
        self.save()
        logger.info("Task: like")

    def dislike(self):
        """
        Уменьшает рейтинг объекта на 1 и сохраняет изменения.

        Эта функция не принимает никаких параметров.

        Эта функция не возвращает значений.
        """
        self.rating = models.F("rating") - 1
        self.save()
        logger.info("Task: dislike")

    def preview(self):
        """
        Возвращает предпросмотр первых 123 символов текста, за которым следует '...'.

        :return: Строка, представляющая предпросмотр текста.
        """
        logger.info("Task: preview")
        return self.text[0:123] + "..."

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        """
        Возвращает строковое представление объекта.
        """
        logger.info(f"Comment: {self.text}")
        return f"{self.commentUser} : {self.text[0:123]}..."

    def like(self):
        """
        Увеличивает рейтинг объекта на 1 и сохраняет изменения.

        Параметры:
            None

        Возвращает:
            None
        """
        self.rating = models.F("rating") + 1
        self.save()
        logger.info("Task: like")

    def dislike(self):
        """
        Уменьшает рейтинг объекта на 1 и сохраняет изменения.

        Параметры:
            self (object): Экземпляр объекта, вызывающий функцию.

        Возвращает:
            None
        """
        self.rating = models.F("rating") - 1
        self.save()
        logger.info("Task: dislike")

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class PostCategory(models.Model):
    postThrow = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Subscriber(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="subscriptions"
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="subscriptions"
    )

    # email = models.EmailField()

    def __str__(self):
        """
        Возвращает строковое представление объекта.
        """
        logger.info(f"Subscriber: {self.user}")
        return str(self.user)

    class Meta:
        verbose_name = "Подписчик"
        verbose_name_plural = "Подписчики"


# @register(Category)
# class CategoryTranslationOptions(TranslationOptions):
#     fields = ('name',)  # указываем, какие именно поля надо переводить в виде кортежа
#
#
# @register(MyModel)
# class MyModelTranslationOptions(TranslationOptions):
#     fields = ('name',)

News/forms.py
from django import forms
from django.core.exceptions import ValidationError

from NewsPortal.settings import logger
from .models import Post


class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=128)
    logger.info("Form: NewsForm")

    class Meta:
        model = Post
        fields = [
            "author",
            "title",
            "text",
            "postCategory",
        ]
        labels = {
            "author": "Автор",
            "title": "Заголовок",
            "text": "Текст",
            "postCategory": "Категория",
        }

    def clean(self):
        """
        Очищает введенные данные и убеждается, что описание не совпадает с заголовком.

        Возвращает:
            cleaned_data (dict): Очищенные введенные данные.

        Выбрасывает:
            ValidationError: Если описание совпадает с заголовком.
        """
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        text = cleaned_data.get("text")
        logger.info(f"Title: {title}")

        if text == title:
            logger.warning("text == title")
            raise ValidationError("Описание не может совпадать с заголовком.")

        return cleaned_data

templates/news/all_news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %} <!-- Подключаем фильтр цензуры -->
{% load custom_tags %}
{% load i18n %}
{% load tz %}
{% block title %}
	{% trans "News" %}
{% endblock title %}

{% block content %}
	<h1>{% trans "All news" %}</h1>
	<hr>
	<form action="" method="get">
		{{ filterset.form.as_p }}
		<input type="submit" value="Найти"/>
	</form>

	{% if perms.News.add_post %}
		<br/>
		<button onclick="window.location.href='{% url 'news_create' %}'">{% trans "Add news" %}</button>
	{% endif %}

	{% if all_news %}
		<br/>
		<table>

			<tr>
				<td style="text-align: center;">{% trans "Caption" %}</td>
				<td style="text-align: center; width: 300px;">{% trans "Publication date" %}</td>
				<td style="width: 300px;">{% trans "Summary" %}</td>
				{% if perms.News.change_post or perms.News.delete_post %}
					<td>{% trans "Actions" %}</td>
				{% endif %}
			</tr>


			{% for one_news in all_news %}
				<tr>
					<td><a href="/news/{{ one_news.pk }}">{{ one_news.title|censorship }}</td>
					<!-- Цензура заголовков -->
					<td style="text-align: center; width: 300px;">{{ one_news.dateCreation|date:'H:i  d M Y' }}</td>
					<!-- Отображаем дату у каждой новости день. месяц. год-->
					<td style="width: 300px;"><a
						href="/news/{{ one_news.pk }}">{{ one_news.text|truncatechars:20|censorship }}</td>
					<!-- Цензура текста новостей -->
					<td>
						{% if perms.News.change_post %}
							<button
								onclick="window.location.href='{% url 'news_update' pk=one_news.pk %}'">{% trans "Change" %}</button>
						{% endif %}
						{% if perms.News.delete_post %}
							<button onclick="window.location.href='{% url 'news_delete' one_news.pk %}'">{% trans "Delete" %}</button>
						{% endif %}
					</td>
				</tr>
			{% endfor %}

		</table>
	{% else %}
		<h2>{% trans "No news yet" %}</h2> <!-- Если новостей нет, так и напишем -->
	{% endif %}

	{% if page_obj.has_previous %}
		<a href="?{% url_replace page=1 %}">1</a>
		{% if page_obj.previous_page_number != 1 %}
			...
			<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
		{% endif %}
	{% endif %}

	{{ page_obj.number }}

	{% if page_obj.has_next %}
		<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
		{% if paginator.num_pages != page_obj.next_page_number %}
			...
			<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
		{% endif %}
	{% endif %}

{% endblock content %}

templates/news/news_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}
	{% trans 'Deleting news' %} {{ object.pk }}
{% endblock title %}

{% block content %}
	<h1>{% trans 'Deleting news' %} {{ object.pk }}</h1>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
	    <p>{% trans 'Remove' %} "{{ object.title }}"?</p>
        <input type="submit" value="Delete"/>
    </form>
{% endblock content %}

templates/news/news_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}

{% block title %}
	{% trans 'News' %} {{ object.pk }}
{% endblock title %}

{% block content %}
	<h1>{% trans 'News' %} {{ object.pk }} <br> {{ object.title }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

templates/news/one_news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %} <!-- Подключаем фильтр цензуры -->
{% load custom_tags %}
{% load i18n %}
{% load tz %}
{% block title %}
	{% trans 'News' %} {{ one_news.pk }}
{% endblock title %}

{% block menu %}
    {% for one_news in all_news %}
        <li><a class="dropdown-item" href="/news/{{ one_news.pk }}">{{ one_news.title }}</a></li>
    {% endfor %}
{% endblock menu %}

{% block content %}
	<h4>{% trans 'Caption: ' %}</h4>{{ one_news.title|censorship }}</br> <!-- Цензура заголовков -->
    <h4>Текст: </h4>{{ one_news.text|censorship }}</br> <!-- Цензура текста новости -->
	<h4>{% trans 'Date of creation: ' %}</h4>{{ one_news.dateCreation|date:'H:i  d M Y' }}</br>
    <!-- Время и дата создания новости. Время, чтобы было видно, что работает сортировка, а то все новости в один день -->
	<h4>{% trans 'Rating: ' %}</h4>{{ one_news.rating }}</br>
	<h4>{% trans 'Category: ' %}</h4>{{ one_news.get_categoryType_display }}</br>  <!-- Выводим человеческое значение -->

{% endblock content %}

templates/news/subscriptions.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}
	{% trans 'Subscriptions' %}
{% endblock title %}

{% block content %}
	<h4>{% trans 'User email:' %} {{ user.email }}</h4>

	{% for category in categories %}
		<p>
			{{ category.name }}
		<form method="post">
			{% csrf_token %}
			<input type="hidden" name="category_id" value="{{ category.id }}"/>

			{% if category.user_subscribed %}
				<button disabled>{% trans 'Subscribe' %}</button>
				<button name="action" value="unsubscribe">{% trans 'Unsubscribe' %}</button>
			{% else %}
				<button name="action" value="subscribe">{% trans 'Subscribe' %}</button>
				<button disabled>{% trans 'Unsubscribe' %}</button>
			{% endif %}
		</form>
		</p>
	{% endfor %}
{% endblock content %}